### ISSUE TITLE
writeData issue will have issues if loaders are mixed

### ISSUE THREAD

**Issue by ravi-polampelli** [EaseTech/easytest#36]
WriteData fix looks really good and neat now withAfterClass.

But, it has issue if user gives different data loaders at class level and method level, or gives different file names.

For ex: TestExcelDataLoader
if we uncomment CSV loader

```
@DataLoader(filePaths={"overrideExcelData.csv"} , loaderType=LoaderType.CSV)
public void getExcelTestDataWithDouble(@Param(name = "libraryId")
```

and comment EXCEL loader

```
//@DataLoader(filePaths = { "testExcelData.xls" }, loaderType = LoaderType.EXCEL)
public Item getExcelTestDataWithReturnType(@Param(name = "libraryId")
```

Now writeData will not work as loader is CSV and we don't find this getExcelTestDataWithReturnType in csv file.

I see this is a bit shaky in data loaders when we combine them.
Generally, I don't think people will combine loaders/file in this way, in my view, this is not a real time scenario. but since we are providing this flexibility of data loaders at class level and method level, we need to handle it.

Actually, this is the reason I kept that IF condition in actualData related to issue#32. But that is anyhow doesn't solve this problem, and what ever solution you have provided with writableData and removed IF condition looks fine.

In my view, current solution provided by you withAfterClass is good enough. we need to think 
1) whether really we need to provide flexibility of loading data from class level and method level.

**Comment by anujgandharv** [comment]
A good observation Ravi. Its nice that we have caught this early.
As per the flexibility of overriding the data at the method level goes, it has to be supported. So we cannot get away with it. I have looked at the issue, and the main bottleneck between achieving this is how and where we are writing our output data. I have it working for XML Data loader. So I have test cases where I load test data from different files both at the class level as well as at method level and the data is written back to the file from which the data was loaded.

There is some problem in the way we load and write data to the Excel file. That's what I am looking at currently. I will keep you posted of the updates.

By the way I agree with the fact that we can, for the time being, restrict providing one type of file(XML, excel or csv) per class instead of providing all of them and also expecting the data to be written. If you have some ideas do share.

**Comment by ravi-polampelli** [comment]
I think problem should be same in any loader, excel or xml..i think so.
what ever loaded lastly will become effective.

**Comment by anujgandharv** [comment]
Hi Ravi. EasyTest now supports writing data to files specified at class level as well as method level. It works as following:
- If the test method does not have a data loader annotation and it returns some test data, that test data is written to the first file specified by the DataLoader annotation at the class level.
- If the test method has a DataLoader annotation and returns some test data, that test data will be written to the file specified by the dataLoader annotation at the method level.
- If there are two test methods in the same class that takes data from two different types of files(XML, Excel) then the output data will be written to the correct file.

I have checked in the code and will be creating a Pull Request for you soon. Please review and send across any comments, if any.

Cheers!
Anuj

**Comment by anujgandharv** [comment]
This is now done.
