### ISSUE TITLE
Remove @Override annotation

### ISSUE THREAD

**Issue by ravi-polampelli** [EaseTech/easytest#4]
The method convertTo() of type AbstractConverter<Type> must override a superclass method, so remove @Override annotation.

For following class files
1) AbstractConverter.java -- covertTo() method
2) CVSDataLoader.java - loadData() method
3) EmptyLoader,java - loadData method
4) CustomCVSDataLoader.java - loadData method
5) CustomObjectDataLoader.java loadData method
6) ItemConverter.java - convert method

**Comment by anujgandharv** [comment]
Hi Ravi,
 Instead of removing these annotations, I would suggest you to change the compiler compliance level in your IDE. For eg. if you are using Eclipse/STS, you can do that by going to the following menu options:
Window -> prefrences 
On the left side click on java -> compiler

You will see an option Compiler compliance level. Change that to 1.6 and everything should then start working and you should not get the compilation problems.

@Override annotation is present in java.lang package and is available since 1.5 and it is a standard compile time annotation which will be discarded by the compiler eventually.

**Comment by ravi-polampelli** [comment]
Anuj,

Ya, I see the error is coming for compilation level 1.5, and can be solved by moving to 1.6.
But, As mentioned, I am using JDK 1.5 compilation level.
As general still some(majority) people are using JDK 1.5, hence, I think it is better to have our compilation level at 1.5.
Removing that Override annotation will make us compatible with both 1.5 and higher, so, I think it is better to maintain source code compatible from 1.5 and higher. I also don't think this annotation bringing us any extra advantage. 

Let me know your views on this.

**Comment by anujgandharv** [comment]
Hi Ravi,
 The users of easytest will not get any compilation error because they will
be using the compiled code(in the form of JAR file) and in the compiled
code, @Override annotation will not be there, as it would have already been
removed by the compiler. The annotation is a developer level annotation
which helps during the development process and has no significance in the
compiled code. Here is the link of why Overrides should be used during
development time:  http://www.javapractices.com/topic/TopicAction.do?Id=223

Thanks,
Anuj

On Wed, Aug 29, 2012 at 4:04 PM, ravi-polampelli
notifications@github.comwrote:

> Anuj,
> 
> Ya, I see the error is coming for compilation level 1.5, and can be solved
> by moving to 1.6.
> But, As mentioned, I am using JDK 1.5 compilation level.
> As general still some(majority) people are using JDK 1.5, hence, I think
> it is better to have our compilation level at 1.5.
> Removing that Override annotation will make us compatible with both 1.5
> and higher, so, I think it is better to maintain source code compatible
> from 1.5 and higher. I also don't think this annotation bringing us any
> extra advantage.
> 
> Let me know your views on this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/EaseTech/easytest/issues/4#issuecomment-8126241.

## 

_Anuj Kumar_

**Comment by ravi-polampelli** [comment]
Ok got your point, as a best practice, you want to continue this.
I will create new workspace with 1.6 compilation level, and continue.

Cheers,
Ravi.
