### ISSUE TITLE
@BeforeClass and @AfterClass methods are executing for every test method

### ISSUE THREAD

**Issue by ravi-polampelli** [EaseTech/easytest#43]
I tried to create a setup() method with annotation @BeforeClass and a teatDown() method with annotaion @AfterClass, I assumed they will be executed once per class, but they are exeucting for each test method. what could be the problem?

**Comment by anujgandharv** [comment]
I think I know why this is happening. The reason is we are creating a new Runner for each test method that takes parameter. This is a major issue. We have to fix this. Let me have a look at this.

**Comment by ravi-polampelli** [comment]
Hi Anuj, did u get the clue?

**Comment by anujgandharv** [comment]
Hi Ravi. Yes I have found the issue and have also fixed it just 5 min back. I am getting a minor issue that I am looking at. The fix should be available latest by tomorrow morning. :). Also as a result of this issue, the runner has become a lot simplified.

**Comment by ravi-polampelli** [comment]
Good to know that.

**Comment by anujgandharv** [comment]
Hi Ravi. The Runner is fixed. I created a new Runner altogether as it was easier to do. I will remove one of them soon. In the mean time you can use DataDrivenTestRunner class to run your tests instead of DataDrivenTest. All the examples in the test package is also using the DataDrivenTestRunner class.

**Comment by ravi-polampelli** [comment]
I checked, its working fine. Great work in quick time. Can you put brief  about the solution here?

**Comment by anujgandharv** [comment]
So the problem was due to the fact that we were creating a separate Runner for each method that expected input test data. That led to the fact that each method effectively was treated as a test class, and therefore the beforeClass and afterClass methods were run for each test method that was expecting input test data.

So the solution was to have a single Runner for all the methods. And thats exactly what I did. 
I think theres an issue with JUnit's BeforeClass method for Suite Runner, as it was being run twice even after I had fixed the acual issue. So in order to bypass it, I simply did an override of beforeClass method.

Cheers!
